Controllers/AdminController.cs
using ProjetC_MVCSalleSport.Models;
using System.Linq;
using System.Web.Mvc;

namespace ProjetC_MVCSalleSport.Controllers
{
    public class AdminController : Controller
    {
        private readonly ContexteDeBaseDeDonnees _context;
        public AdminController()
        {
            _context = new ContexteDeBaseDeDonnees();
        }

        [HttpGet]
        public ActionResult ListeCours()
        {
            var cours = _context.Cours.ToList();
            return View("ListeCours", cours);
        }


        [HttpGet]
        public ActionResult Ajouter()
        {
            return View("AjouterCours");
        }


        [HttpPost]
        public ActionResult AjouterCours(Cours cours)
        {


            if (ModelState.IsValid)
            {
                _context.Cours.Add(cours);
                _context.SaveChanges();
                return RedirectToAction("ListeCours");
            }
            return View(cours);
        }
<<<<<<< HEAD
=======
        [HttpGet]
        public ActionResult Supprimer()
        {
            var listeCours = _context.Cours.ToList();
            return View("SupprimerCours", listeCours);
        }


        [HttpPost]
        public ActionResult SupprimerCours(int idCours)
        {
            var coursASupprimer = _context.Cours.Find(idCours);

            if (coursASupprimer != null)
            {
                _context.Cours.Remove(coursASupprimer);
                _context.SaveChanges();
            }

            return RedirectToAction("ListeCours");
        }
>>>>>>> 9302fff822ecb79e10b2c0f6ae0ee2f4cc840620
    }
}

Controllers/AuthController.cs
using ProjetC_MVCSalleSport.Models;
using System.Linq;
using System.Web.Mvc;

namespace ProjetC_MVCSalleSport.Controllers
{
    public class AuthController : Controller
    {
        private ContexteDeBaseDeDonnees db = new ContexteDeBaseDeDonnees();
        // GET: /Auth/ChooseUser
        public ActionResult ChooseUser()
        {
            return View();
        }

        // GET: /Auth/Login
        public ActionResult Login()
        {
            return View();
        }

        // POST: /Auth/Login
        [HttpPost]
        public ActionResult Login(Membre membre)
        {
            var membreTrouve = db.Membres.FirstOrDefault(m => m.mail == membre.mail && m.motDePasse == membre.motDePasse);

            if (membreTrouve != null)
            {
                // Si le membre est trouvé, redirigez-le vers une autre vue ou effectuez d'autres actions
                Session["UserType"] = "membre";
                return RedirectToAction("Index", "Home"); // Redirection vers la page d'accueil par exemple
            }
            else
            {
                ModelState.AddModelError("", "Email ou mot de passe incorrect");
                return View(membre);
            }
        }

        // GET: /Auth/SignUp
        public ActionResult SignUp()
        {
            return View();
        }

        // POST: /Auth/SignUp
        [HttpPost]
        public ActionResult SignUp(Membre membre)
        {
            if (ModelState.IsValid)
            {
                var existingMember = db.Membres.FirstOrDefault(m => m.mail == membre.mail);
                if (existingMember != null)
                {
                    ModelState.AddModelError("", "Cet e-mail est déjà utilisé pour un autre compte.");
                    return View(membre);
                }

                db.Membres.Add(membre);
                db.SaveChanges();

                // Rediriger vers une page de confirmation ou une autre page appropriée
                return RedirectToAction("About", "Home"); // Redirection vers la page d'accueil par exemple
            }

            return View(membre);
        }

        // GET: /Auth/Confirmation
        public ActionResult Confirmation()
        {
            return View();
        }
        // GET: /Auth/Logout
        public ActionResult Logout()
        {
            // Code de déconnexion
            Session.Clear(); // Effacer toutes les variables de session
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/CoachController.cs
using ProjetC_MVCSalleSport.Models;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;


namespace ProjetC_MVCSalleSport.Controllers
{
    public class CoachController : Controller
    {
        private readonly ContexteDeBaseDeDonnees _context;

        public CoachController()
        {
            _context = new ContexteDeBaseDeDonnees();
        }
        // GET: /Auth/LoginCoach
        public ActionResult LoginCoach()
        {
            return View();
        }

        // POST: /Coach/LoginCoach
        [HttpPost]
        public ActionResult LoginCoach(Coach coach)
        {
            var coachTrouve = _context.Coaches.FirstOrDefault(c => c.mail == coach.mail && c.motDePasse == coach.motDePasse);

            if (coachTrouve != null)
            {
                // Redirect to the appropriate action and controller after successful login
                Session["UserType"] = "coach";
                return RedirectToAction("Index", "Home"); // Redirection vers la page d'accueil par exemple

            }
            else
            {
                ModelState.AddModelError("", "Email ou mot de passe incorrect");
                return View(coach);
            }
        }

        [HttpGet]
        public ActionResult ListeCoaches()
        {
            var coaches = _context.Coaches.ToList();
            return View("ListeCoaches", coaches);
        }

        [HttpGet]
        public ActionResult Ajouter()
        {
            return View("AjouterCoach");
        }

        [HttpPost]
        public ActionResult AjouterCoach(Coach coach)
        {
            if (ModelState.IsValid)
            {
                _context.Coaches.Add(coach);
                _context.SaveChanges();
                return RedirectToAction("ListeCoaches");
            }
            return View(coach);
        }
<<<<<<< HEAD
=======
        [HttpGet]
        public ActionResult Supprimer()
        {
            var ListeCoaches = _context.Coaches.ToList();
            return View("SupprimerCoach", ListeCoaches);
        }


        [HttpPost]
        public ActionResult SupprimerCoach(int idCoach)
        {
            var coachASupprimer = _context.Coaches.Include(c => c.cours).FirstOrDefault(c => c.id_coach == idCoach);

            if (coachASupprimer != null)
            {
                foreach (var cours in coachASupprimer.cours.ToList())
                {
                    _context.Cours.Remove(cours);
                }

                _context.Coaches.Remove(coachASupprimer);
                _context.SaveChanges();
            }

            return RedirectToAction("ListeCoaches");
        }


>>>>>>> 9302fff822ecb79e10b2c0f6ae0ee2f4cc840620
        // GET: /Coach/Logout
        public ActionResult Logout()
        {
            // Code de déconnexion
            Session.Clear(); // Effacer toutes les variables de session
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/CoursController.cs
using ProjetC_MVCSalleSport.Models;
using System.Linq;
using System.Web.Mvc;

namespace ProjetC_MVCSalleSport.Controllers
{
    public class CoursController : Controller
    {
        private ContexteDeBaseDeDonnees db = new ContexteDeBaseDeDonnees();

        // GET: Cours
        public ActionResult Index()
        {
            var cours = db.Cours.Include("Coaches").ToList();
            return View(cours);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FitLAND</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container-fluid">
            @Html.ActionLink("FitLAND", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"> </span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
<<<<<<< HEAD
                <ul class="navbar-nav ">
                    <li>@Html.ActionLink("Acceuil", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (Session["UserType"] != null)
                    {
                        var userType = Session["UserType"].ToString();
                        if (userType == "admin")
                        {
                            <li>@Html.ActionLink("Ajouter Membre", "Ajouter", "Membre", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Liste Membres", "ListeMembres", "Membre", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Ajouter Coach", "Ajouter", "Coach", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Liste Coaches", "ListeCoaches", "Coach", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Logout", "Logout", "LoginAdmin", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Ajouter Cours", "Ajouter", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                        }

                        if (userType == "membre")
                        {
                            <li>@Html.ActionLink("Planning", "Index", "Planning", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Logout", "Logout", "Auth", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                        if (userType == "coach")
                        {
                            <li>@Html.ActionLink("Planning", "Index", "Planning", new { area = "" }, new { @class = "nav-link" })</li>
=======
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (Session["UserType"] != null)
                    {
                        var userType = Session["UserType"].ToString();



                        if (userType == "admin")
                        {
                            <li>@Html.ActionLink("Ajouter Membre", "Ajouter", "Membre", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Liste Membres", "ListeMembres", "Membre", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Ajouter Coach", "Ajouter", "Coach", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Liste Coaches", "ListeCoaches", "Coach", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Logout", "Logout", "LoginAdmin", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Ajouter Cours", "Ajouter", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Liste Cours", "ListeCours", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Supprimer Cours", "Supprimer", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Supprimer Membre", "Supprimer", "Membre", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Supprimer Coach", "Supprimer", "Coach", new { area = "" }, new { @class = "nav-link" })</li>
                        }

                        if (userType == "membre")
                        {
                            int userId = Convert.ToInt32(Session["UserID"]);
                            <li>@Html.ActionLink("Planning", "Index", "Cours", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Consulter Progrès", "ConsulterProgres", "Membre", new { id = userId }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Logout", "Logout", "Auth", new { area = "" }, new { @class = "nav-link" })</li>

                        }
                        if (userType == "coach")
                        {
                            <li>@Html.ActionLink("Planning", "Index", "Cours", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Ajouter Progrés", "AjouterProgres", "Membre", new { area = "" }, new { @class = "nav-link" })</li>
>>>>>>> 9302fff822ecb79e10b2c0f6ae0ee2f4cc840620
                            <li>@Html.ActionLink("Logout", "Logout", "Coach", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                    }
                    else
                    {
<<<<<<< HEAD
                        <li>@Html.ActionLink("Connexion", "ChooseUser", "Auth", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Inscription", "SignUp", "Auth", new { area = "" }, new { @class = "nav-link" })</li>
=======
                        <li>@Html.ActionLink("Login", "ChooseUser", "Auth", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Register Member ", "SignUp", "Auth", new { area = "" }, new { @class = "nav-link" })</li>
>>>>>>> 9302fff822ecb79e10b2c0f6ae0ee2f4cc840620

                    }
                </ul>

            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
<<<<<<< HEAD
      
=======
        <hr />
        <footer>
           
        </footer>
>>>>>>> 9302fff822ecb79e10b2c0f6ae0ee2f4cc840620
    </div>








    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>