Models/Membre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjetC_MVCSalleSport.Models
{
    [Table("membre")]
    public class Membre
    {
        public Membre()
        {
        }
        [Key]
        public int id_membre { get; set; }

        public String nom { get; set; }

        public String prenom { get; set; }

        public int telephone { get; set; }

        public String motDePasse { get; set; }

        public String mail { get; set; }
        public ICollection<Abonnement> Abonnements { get; set; }


        public ICollection<Progrés> Progres { get; set; }
        public ICollection<Admin> admins { get; set; }

        public ICollection<Cours> Cours { get; set; }





    }
}

Controllers/MembreController.cs
using ProjetC_MVCSalleSport.Models;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;


namespace ProjetC_MVCSalleSport.Controllers
{
    public class MembreController : Controller
    {
        private readonly ContexteDeBaseDeDonnees _context;

        public MembreController()
        {
            _context = new ContexteDeBaseDeDonnees();
        }

        [HttpGet]
        public ActionResult ListeMembres()
        {
            var membres = _context.Membres.ToList();
            return View("listeMembres", membres);
        }


        [HttpGet]
        public ActionResult Ajouter()
        {
            return View("AjouterMembre");
        }


        [HttpPost]
        public ActionResult AjouterMembre(Membre membre)
        {
            if (ModelState.IsValid)
            {
                _context.Membres.Add(membre);
                _context.SaveChanges();
                return RedirectToAction("ListeMembres");
            }
            return View(membre);
        }
        [HttpGet]
        public ActionResult Supprimer()
        {
            var ListeMembres = _context.Membres.ToList();
            return View("SupprimerMembre", ListeMembres);
        }


        [HttpPost]
        public ActionResult SupprimerMembre(int? idMembre)
        {
            var membreASupprimer = _context.Membres.Find(idMembre);

            if (membreASupprimer != null)
            {
                _context.Membres.Remove(membreASupprimer);
                _context.SaveChanges();
            }

            return RedirectToAction("ListeMembres");
        }
        [HttpPost]
        public ActionResult AjouterProgres(Progrés progres)
        {
            if (ModelState.IsValid)
            {
                // Ajouter le progrès au contexte de la base de données
                _context.Progres.Add(progres);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(progres);
        }

        [HttpGet]
        public ActionResult ConsulterProgres(int id)
        {
            var membre = _context.Membres.Include(m => m.Progres).FirstOrDefault(m => m.id_membre == id);
            return View("ConsulterProgres", membre);
        }


    }
}

Views/Membre/AjouterMembre.cshtml
@model ProjetC_MVCSalleSport.Models.Membre

@using (Html.BeginForm("AjouterMembre", "Membre", FormMethod.Post))
{
    @Html.LabelFor(model => model.nom)
    @Html.TextBoxFor(model => model.nom)
    <br />

    @Html.LabelFor(model => model.prenom)
    @Html.TextBoxFor(model => model.prenom)
    <br />

    @Html.LabelFor(model => model.telephone)
    @Html.TextBoxFor(model => model.telephone)
    <br />

    @Html.LabelFor(model => model.motDePasse)
    @Html.TextBoxFor(model => model.motDePasse)
    <br />

    @Html.LabelFor(model => model.mail)
    @Html.TextBoxFor(model => model.mail)
    <br />

    <input type="submit" value="Ajouter" />
}

Views/Membre/AjouterProgres.cshtml
@model ProjetC_MVCSalleSport.Models.Progrés

@{
    ViewBag.Title = "Ajouter Progrès";
}

<h2>Ajouter Progrès à un Membre</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.id_membre, "ID Membre", htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.id_membre, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.id_membre, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.poids, "Poids", htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.poids, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.poids, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.imc, "IMC", htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.imc, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.imc, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.date, "Date", htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Ajouter" class="btn btn-primary" />
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

Views/Membre/ConsulterProgres.cshtml
@model ProjetC_MVCSalleSport.Models.Membre

@{
    ViewBag.Title = "Consulter Progrès";
}

<h2>Progrès </h2>

@if (Model.Progres != null && Model.Progres.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Poids</th>
                <th>IMC</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var progres in Model.Progres)
            {
                <tr>
                    <td>@progres.date.ToShortDateString()</td>
                    <td>@progres.poids</td>
                    <td>@progres.imc</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Aucun progrès à afficher pour ce membre.</p>
}

<div>
    @Html.ActionLink("Retour à homePage", "index")
</div>

Views/Membre/ListeMembres.cshtml
@model List<ProjetC_MVCSalleSport.Models.Membre>

<!DOCTYPE html>
<html>
<head>
    <title>Liste des Membres</title>
</head>
<body>
    <h1>Liste des Membres</h1>

    @if (Model != null && Model.Any())
    {
        <table>
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Téléphone</th>
                    <th>Mail</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var membre in Model)
                {
                    <tr>
                        <td>@(membre.nom ?? "N/A")</td>
                        <td>@(membre.prenom ?? "N/A")</td>
                        <td>@(membre.telephone != null ? membre.telephone.ToString() : "N/A")</td>
                        <td>@(membre.mail ?? "N/A")</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Aucun membre à afficher.</p>
    }
</body>
</html>

Views/Membre/SupprimerMembre.cshtml
@model List<ProjetC_MVCSalleSport.Models.Membre>

    <!DOCTYPE html>
    <html>
    <head>
        <title>Liste des Membres</title>
    </head>
    <body>
        <h1>Liste des Membres</h1>

        @if (Model != null && Model.Any())
        {
            <table>
                <thead>
                    <tr>
                        <th>id_membre</th>
                        <th>nom</th>
                        <th>prenom</th>
                        <th>telephone</th>
                        <th>mail</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var membre in Model)
                    {
                        <tr>
                            <td>@(membre.id_membre != null ? membre.id_membre.ToString() : "N/A")</td>
                            <td>@(membre.nom ??  "N/A")</td>
                            <td>@(membre.prenom ?? "N/A")</td>
                            <td>@(membre.telephone != null ? membre.telephone.ToString() : "N/A")</td>
                            <td>@(membre.mail ?? "N/A")</td>

                        </tr>
                    }
                </tbody>
            </table>

            <h2>Supprimer un membre</h2>
            using (Html.BeginForm("SupprimerMembre", "Membre", FormMethod.Post))
            {
                <label for="idMembre">ID du membre à supprimer :</label>
                <input type="text" id="idMembre" name="idMembre">
                <button type="submit">Supprimer</button>
            }
        }
        else
        {
            < p > Aucun membre à afficher.</ p >
        }
    </body>
</html>